"use client";

import { Outfit } from "next/font/google";
import StyledComponentsRegistry from "@/lib/registry";
import Container from "@/components/Container";
import { NavBar, NavBarTriggerButton } from "@/components/NavBar";
import GlobalStyle from "./globalStyle";
import { useState } from "react";

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [navOpen, setNavOpen] = useState(false);
  return (
    <html lang="en" className={outfit.className}>
      <GlobalStyle />
      <body>
        <StyledComponentsRegistry>
          <Container>
            <NavBarTriggerButton onClick={(e) => setNavOpen(!navOpen)} />
            <NavBar navOpen={navOpen} setNavOpen={setNavOpen} />
            {children}
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
